export const FETCH_ENTRIES_REQUEST = 'FETCH_ENTRIES_REQUEST'
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS'
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE'

export const ADD_ENTRY_REQUEST = 'ADD_ENTRY_REQUEST'
export const ADD_ENTRY_SUCCESS = 'ADD_PILLAR_ITEM_SUCCESS'
export const ADD_ENTRY_FAILURE = 'ADD_ENTRY_FAILURE'

export const REMOVE_ENTRY_REQUEST = 'REMOVE_ENTRY_REQUEST'
export const REMOVE_ENTRY_SUCCESS = 'REMOVE_ENTRY_SUCCESS'
export const REMOVE_ENTRY_FAILURE = 'REMOVE_ENTRY_FAILURE'

export const EDIT_ENTRY_REQUEST = 'EDIT_ENTRY_REQUEST'
export const EDIT_ENTRY_SUCCESS = 'EDIT_ENTRY_SUCCESS'
export const EDIT_ENTRY_FAILURE = 'EDIT_ENTRY_FAILURE'

export const CHANGE_DAY_REQUEST = 'CHANGE_DAY_REQUEST'
export const CHANGE_DAY_SUCCESS = 'CHANGE_DAY_SUCCESS'
export const CHANGE_DAY_FAILURE = 'CHANGE_DAY_FAILURE'
