export const ADD_PILLAR_ITEM_SUCCESS = 'ADD_PILLAR_ITEM_SUCCESS'
export const REMOVE_PILLAR_ITEM_SUCCESS = 'REMOVE_PILLAR_ITEM_SUCCESS'
export const REQUEST_ITEMS = 'REQUEST_ITEMS'
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS'

